import React from 'react';
import './css/master.css';

function About() {
	return (
		<div className="content">
			<h1 className="header">The Ethereum Yield Curve</h1>
			<h1 className="subHeader">Rate Exposure With Zero Coupon Bonds for Ethereum Assets</h1>
			<h1 className="subSubHeaderRight"><span>About Zero Coupon Bonds</span></h1>
			<p>
				Feldmex Zero Coupon Bonds (ZCBs) payout a specific amount of a specific asset at a specific time with no other payments.
				Each ZCB is matched 1:1 with its payout.
				Users may mint ZCBs by depositing Aave ATokens in the Capital Handler contract.
				After minting ZCBs by depositing funds users still collect the yield generated by deposited funds.
				If a user then sells their collateralised ZCBz they collect the yield generated by the funds used to collateralise their sold ZCBs.
				If a user buys ZCBs direclty off the market they do not collect any yield generated by funds collateralising ZCBs prior to the maturity.
			</p>

			<h1 className="subSubHeaderLeft"><span>How It Works</span></h1>
			<p>
				Feldmex Zero Coupon bonds are backed by Aave ATokens.
				In order to sell ZCBs a user must deposit an amount of ATokens equal to the amount of ZCBs they wish to sell.
				Once a user has deposited collateral and they sell ZCBs against their collateral they retain the right to any yield generated by their collateral over the period leading up to the maturity.
				As explained earlier ZCB holders may exchange their ZCBs 1 to 1 with ATokens after the maturity.
			</p>

			<h1 class="subSubHeaderRight"><span>Meta Mask</span></h1>
			<p>
				In order to use this website users must use the Meta-Mask browser extention.
				For more information about the Meta Mask browser extention click <a href="https://www.youtube.com/watch?v=aw7Sh4APyPQ" target="_blank" rel="noopener noreferrer">here</a>.
				Currently Feldmex is running on the kovan testnetwork. To connect to this network you must add it in Meta Mask.
				To switch to the Kovan testnet follow the directions below: 
			</p>

			<ol>
				<li>Open Meta Mask</li>
				<li>Click on the dropdown menu in the top center of the Meta Mask pop up</li>
				<li>Click on the option titled "Kovan Test Network"</li>
			</ol>

			<p>
				Every time you use Feldmex be sure that you have Kovan as your selected network.
			</p>

		</div>
		);
}

export default About;
