import React from 'react';
import './css/master.css';

function About() {
	return (
		<div className="content">
			<h1 className="header">The Ethereum Yield Curve</h1>
			<h1 className="subHeader">Rate Exposure With Zero Coupon Bonds for Ethereum Assets</h1>
			<h1 className="subSubHeaderRight">About Zero Coupon Bonds</h1>
			<p>
				Feldmex Zero Coupon Bonds (ZCBs) payout a specific amount of a specific asset at a specific time with no other payments.
				Each ZCB is matched 1:1 with its payout.
				Users may mint ZCBs by depositing Aave ATokens in the Capital Handler contract.
				After minting ZCBs by depositing funds users still collect the yield generated by deposited funds.
				If a user then sells their collateralised ZCBz they collect the yield generated by the funds used to collateralise their sold ZCBs.
				If a user buys ZCBs direclty off the market they do not collect any yield generated by funds collateralising ZCBs prior to the maturity.
			</p>
		</div>
		);
}

export default About;
